name: CI
on:  [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          version: '22.3.0' #affects the json config format of the agent (reflect-config.json etc)
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Run test and build fat jar
        run: |
          set -e
           
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          # Shell scripting in yml is not fun
          source ./.github/workflows/install_environment.sh
          source ./.github/workflows/test_and_build_fat_jar.sh
          source ./.github/workflows/build_native_image.sh

          # github wants to charge for more lfs uploads 
          # git commit -m "add fat jar and linux executable"
          # git push

